### ISSUE TITLE
dfuzzer seems to crash when DBus services it tests crash

### ISSUE THREAD

**Issue by evverx** [matusmarhefka/dfuzzer#45]
```sh
$ ./build/dfuzzer -v -n org.freedesktop.Avahi
Cannot open suppression file './dfuzzer.conf'
Cannot open suppression file '/home/vagrant/.dfuzzer.conf'
Loading suppressions from file '/etc/dfuzzer.conf'
[SESSION BUS]
Error: The connection does not exist.
Couldn't get the PID of the tested process
[SYSTEM BUS]
[PROCESS: avahi-daemon: running [fedora.local]]
[CONNECTED TO PID: 90831]
Object: /
 Interface: org.freedesktop.DBus.Introspectable
  SKIP Introspect - void method
 Interface: org.freedesktop.Avahi.Server
  SKIP GetVersionString - void method
  SKIP GetAPIVersion - void method
  SKIP GetHostName - void method
  SKIP SetHostName - raised exception 'org.freedesktop.DBus.Error.AccessDenied'
  SKIP GetHostNameFqdn - void method
  SKIP GetDomainName - void method
  SKIP IsNSSSupportAvailable - void method
  SKIP GetState - void method
  SKIP GetLocalServiceCookie - void method
  FAIL GetAlternativeHostName - process exited
   [PID: 90831], [MEM: 4188 kB]
   on input:
    --s**
GLib:ERROR:../glib/gvarianttypeinfo.c:186:g_variant_type_info_check: assertion failed: (0 <= index && index < 24)
Bail out! GLib:ERROR:../glib/gvarianttypeinfo.c:186:g_variant_type_info_check: assertion failed: (0 <= index && index < 24)
Aborted (core dumped)
```
```sh
(gdb) bt
#0  0x00007f8dfcf8c88c in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f8dfcf3f6a6 in raise () at /lib64/libc.so.6
#2  0x00007f8dfcf297d3 in abort () at /lib64/libc.so.6
#3  0x00007f8dfd130d2c in g_assertion_message_expr.cold () at /lib64/libglib-2.0.so.0
#4  0x00007f8dfd1913df in g_assertion_message_expr () at /lib64/libglib-2.0.so.0
#5  0x00007f8dfd1b2176 in g_variant_type_info_check () at /lib64/libglib-2.0.so.0
#6  0x00007f8dfd1b21ef in g_variant_type_info_get_type_string () at /lib64/libglib-2.0.so.0
#7  0x00007f8dfd1a401d in g_variant_is_of_type () at /lib64/libglib-2.0.so.0
#8  0x00007f8dfd1a5220 in valid_format_string () at /lib64/libglib-2.0.so.0
#9  0x00007f8dfd1ab30c in g_variant_get () at /lib64/libglib-2.0.so.0
#10 0x0000000000405cdd in df_fuzz_write_log () at ../src/fuzz.c:368
#11 0x0000000000406cb2 in df_fuzz_test_method
    (statfd=5, buf_size=50000, name=0x7ffc0e5484c9 "org.freedesktop.Avahi", obj=0x409053 "/", intf=0xcf7620 "org.freedesktop.Avahi.Server", pid=90831, void_method=0, execute_cmd=0x0) at ../src/fuzz.c:719
#12 0x0000000000403e2a in df_fuzz (dcon=0xd05140, name=0x7ffc0e5484c9 "org.freedesktop.Avahi", obj=0x409053 "/", intf=0xcf7620 "org.freedesktop.Avahi.Server") at ../src/dfuzzer.c:621
#13 0x00000000004037ce in df_traverse_node (dcon=0xd05140, root_node=0x409053 "/") at ../src/dfuzzer.c:448
#14 0x0000000000402f25 in df_process_bus (bus_type=G_BUS_TYPE_SYSTEM) at ../src/dfuzzer.c:195
#15 0x0000000000402ac2 in main (argc=4, argv=0x7ffc0e548008) at ../src/dfuzzer.c:110
```

**Comment by evverx** [comment]
According to `git bisect` 1c7753a9730d6d0add98b169f8ec32061e90d2ce is the first bad commit

**Comment by evverx** [comment]
I think it would make sense to utilize https://github.com/matusmarhefka/dfuzzer/tree/master/dbus_test_server to test stuff like that. The test server could expose a method calling `abort` and `dfuzzer` could test that method to make sure that it can detect that. In the meantime I'll revert that commit because the memory leak is kind of better than the crash.

**Comment by mrc0mmand** [comment]
> According to `git bisect` [1c7753a](https://github.com/matusmarhefka/dfuzzer/commit/1c7753a9730d6d0add98b169f8ec32061e90d2ce) is the first bad commit

Yeah, the issue is that

https://github.com/matusmarhefka/dfuzzer/blob/03ac9036884b95756768ca1bf3fa2bc1d751d3ca/src/fuzz.c#L563-L564

gets freed once we leave the loop, but it's then utilized via the global variable `df_list` in the `fail_label:` (via `df_fuzz_write_log()`) on crash, where it gets dereferenced, which is... ugly:

```
 Interface: org.freedesktop.Avahi.Server                                                                
  SKIP GetVersionString - void method                                                                   
  SKIP GetAPIVersion - void method                                                                      
  SKIP GetHostName - void method                  
  SKIP SetHostName - raised exception 'org.freedesktop.DBus.Error.AccessDenied'
  SKIP GetHostNameFqdn - void method                                                                    
  SKIP GetDomainName - void method             
  SKIP IsNSSSupportAvailable - void method                                                              
  SKIP GetState - void method                                                                           
  SKIP GetLocalServiceCookie - void method                                                              
  FAIL GetAlternativeHostName - process exited                                                          
   [PID: 876367], [MEM: 4344 kB]                                                                        
   on input:                                                                                            
    --s==877506== Invalid read of size 1                                                                
==877506==    at 0x484A5F6: strlen (vg_replace_strmem.c:494)
==877506==    by 0x4C77207: __vfprintf_internal (vfprintf-internal.c:1647)         
==877506==    by 0x4C6247E: printf (printf.c:33)  
==877506==    by 0x405D51: df_fuzz_write_log (fuzz.c:368)  
==877506==    by 0x406D49: df_fuzz_test_method (fuzz.c:720)
==877506==    by 0x403E39: df_fuzz (dfuzzer.c:621)
==877506==    by 0x4037DD: df_traverse_node (dfuzzer.c:448)                                             
==877506==    by 0x402F34: df_process_bus (dfuzzer.c:195)   
==877506==    by 0x402AD1: main (dfuzzer.c:110)   
==877506==  Address 0x519f1a0 is 0 bytes inside a block of size 48 free'd
==877506==    at 0x48470E4: free (vg_replace_malloc.c:872)         
==877506==    by 0x4AFED2C: g_free (gmem.c:199)                                                         
==877506==    by 0x4B1A50F: g_slice_free1 (gslice.c:1183)                
==877506==    by 0x4B3A9A0: g_variant_release_children (gvariant-core.c:265)
==877506==    by 0x4B3A4E7: UnknownInlinedFun (gvariant-core.c:713)   
==877506==    by 0x4B3A4E7: g_variant_unref (gvariant-core.c:696)
==877506==    by 0x40521E: g_variant_unrefp (util.h:56)    
==877506==    by 0x406C70: df_fuzz_test_method (fuzz.c:565)         
==877506==    by 0x403E39: df_fuzz (dfuzzer.c:621)                                                      
==877506==    by 0x4037DD: df_traverse_node (dfuzzer.c:448)       
==877506==    by 0x402F34: df_process_bus (dfuzzer.c:195)                                                                                                                                                        
==877506==    by 0x402AD1: main (dfuzzer.c:110)
==877506==  Block was alloc'd at
==877506==    at 0x484486F: malloc (vg_replace_malloc.c:381)
==877506==    by 0x4B02428: g_malloc (gmem.c:106)
==877506==    by 0x4B1B074: g_slice_alloc (gslice.c:1072)
==877506==    by 0x4B3C1E1: UnknownInlinedFun (gvariant-core.c:486)
==877506==    by 0x4B3C1E1: g_variant_new_from_bytes (gvariant-core.c:529)
==877506==    by 0x4B3C403: UnknownInlinedFun (gvariant.c:326)
==877506==    by 0x4B3C403: g_variant_new_string (gvariant.c:1270)
==877506==    by 0x4B3DB17: g_variant_valist_new_nnp (gvariant.c:4804)
==877506==    by 0x4B3E571: g_variant_new_va (gvariant.c:5409)
==877506==    by 0x4B3E6C3: g_variant_new (gvariant.c:5344)
==877506==    by 0x4072E7: df_fuzz_create_list_variants (fuzz.c:877)
==877506==    by 0x406EB2: df_fuzz_create_variant (fuzz.c:767)
==877506==    by 0x4065C6: df_fuzz_test_method (fuzz.c:578)
==877506==    by 0x403E39: df_fuzz (dfuzzer.c:621)
==877506== 

```
